// $(function(){$("#WineInformation").keyup(function(e){if(e.keyCode==13){ajax();}});$("#button").click(function(){ajax();});
// function ajax(){var val1=$("#WineInformation1").val(),buttonmsg='search';var e1 = document.getElementById("customselect1");var strUser1 = e1.options[e1.selectedIndex].value;var val2=$("#WineInformation2").val(),buttonmsg='search';var e2 = document.getElementById("customselect2");var strUser2 = e2.options[e2.selectedIndex].value;
// $.ajax({type:"GET",url:"../index.php",data:{WineInformation1:val1,select1:strUser1,WineInformation2:val2,select2:strUser2},beforeSend:function(){$("#button").attr("disabled",true),$("#msg").hide(),$("#button").html("Searching.....");},success:function(a){$("button").attr("disabled",false),$("#button").html(buttonmsg),$("#msg").slideDown(),$("#msg").html(a);},error:function(a){$("button").attr("disabled",false),$("#button").html(buttonmsg),alert("Failed");}});}});

$(function(){$("#WineInformation1").keyup(function(e){if(e.keyCode==13){ajax();}});$("#button").click(function(){ajax();});
function ajax(){var val1=$("#WineInformation1").val(),buttonmsg='search';var e1 = document.getElementById("customselect1");var strUser1 = e1.options[e1.selectedIndex].value;var e2 = document.getElementById("order1");var strUser2 = e2.options[e2.selectedIndex].value;
$.ajax({type:"GET",url:"../cs540_final/index.php",data:{WineInformation1:val1,select1:strUser1,order1:strUser2},beforeSend:function(){$("#button").attr("disabled",true),$("#msg").hide(),$("#button").html("Searching.....");},success:function(a){$("button").attr("disabled",false),$("#button").html(buttonmsg),$("#msg").slideDown(),$("#msg").html(a);},error:function(a){$("button").attr("disabled",false),$("#button").html(buttonmsg),alert("Failed");}});}});


// $(function(){$("#WineInformation1").keyup(function(e){if(e.keyCode==13){ajax();}});$("#button").click(function(){ajax();});
// function ajax(){var val1=$("#WineInformation1").val(),buttonmsg='search';var e1 = document.getElementById("customselect1");var strUser1 = e1.options[e1.selectedIndex].value;var e2 = document.getElementById("order1");var strUser2 = e2.options[e2.selectedIndex].value;
// $.ajax({type:"GET",url:"../test/index.php",data:{WineInformation1:val1,select1:strUser1,order1:strUser2},beforeSend:function(){$("#button").attr("disabled",true),$("#msg").hide(),$("#button").html("Searching.....");},success:function(a){$("button").attr("disabled",false),$("#button").html(buttonmsg),$("#msg").slideDown(),$("#msg").html(a);},error:function(a){$("button").attr("disabled",false),$("#button").html(buttonmsg),alert("Failed");}});}});